Use injector for migration strategy
Hochfrequenz/bo4e_migration_framework pull request #80
Opened 2023-06-02 07:15 UTC by lord-haffi

2023-06-02 07:15 UTC, hf-kklein commented on requirements.in
> +injector
dan auch in der pyproject.toml ergänzen?

2023-06-02 07:16 UTC, hf-kklein commented on src/bomf/__init__.py
> +        validation_manager: Optional[ValidationManager[IntermediateDataSet]] = None,
hast du das getestet?
ich glaube nämlich, du kannst nicht an Generics binden. Deswegen haben wir da, wo wir das Paket nutzen so viele Platzhalter klassen.

2023-06-02 07:16 UTC, hf-kklein requested changes
BItte einen Test der zeigt, dass das klappt ;)

2023-06-02 09:40 UTC, lord-haffi commented on src/bomf/__init__.py
> +        validation_manager: Optional[ValidationManager[IntermediateDataSet]] = None,
Tatsächlich mag injector Generics nicht. Habs aber mit nem kleinen Workaround gefixt. Im Powercloud repo sollte es mit ein paar expliziten Typ-Angaben eigentlich dann auch keine Probleme geben.

2023-06-02 12:49 UTC, hf-kklein commented
OK, it works. Just don't know if it's the right way to do it ;) 
https://github.com/python-injector/injector/issues/218

2023-06-05 13:14 UTC, hf-kklein approved these changes
let's try ;)

2023-06-05 13:22 UTC, merged